### ISSUE TITLE
npm run craco:build fails

### ISSUE THREAD

**Issue by albertocorrales** [hasanayan/craco-plugin-single-spa-application#2]
First of all thanks for this amazing plugin, I was looking for something like this.

I'm trying to test it with a CRA app from scratch. 

`npm run craco:start` seems to work fine and I can run CRA app from Single-Spa.

However, with I run` npm run craco:build`, I'm getting an error: ` Error: Callback was already called.`

My example app is here: https://github.com/albertocorrales/single-spa-cra-example/tree/main/app2

I followed the steps to install, so I'm not sure if there is a bug or I'm missing any configuration.

**Comment by hasanayan** [comment]
Hi @albertocorrales , thanks for giving it a try. I pulled your code and ran it without issues on my machine so your config is fine

Let's try this;

- Create a single-spa-plugin.js file next to your craco.config.js
- Copy and paste contents of src/index.js into single-spa-plugin.js
- Place a `console.log(webpackConfig.module.rules[1].oneOf);` on line 48 in single-spa-plugin.js
- In your craco.config.js replace `singleSpaApplicationPlugin = require('craco-plugin-single-spa-application');` with  `singleSpaApplicationPlugin = require('./single-spa-plugin');`
- Run craco:build and copy the console output here for me to debug

**Comment by albertocorrales** [comment]
Hi @hasanayan, thanks for your quick response. 

I've followed your steps and this is what I'm getting as output:

```
PS C:\F\blog\single-spa-cra-example\app2> npm run craco:build

> app2@0.1.0 craco:build
> craco build

[
  {
    test: [ /\.avif$/ ],
    loader: 'C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\url-loader\\dist\\cjs.js',
    options: {
      limit: 10000,
      mimetype: 'image/avif',
      name: 'static/media/[name].[hash:8].[ext]'
    }
  },
  {
    test: [ /\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/ ],
    loader: 'C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\url-loader\\dist\\cjs.js',
    options: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' }
  },
  {
    test: /\.(js|mjs|jsx|ts|tsx)$/,
    include: 'C:\\F\\blog\\single-spa-cra-example\\app2\\src',
    loader: 'C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\react-scripts\\node_modules\\babel-loader\\lib\\index.js',
    options: {
      customize: 'C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-preset-react-app\\webpack-overrides.js',
      presets: [Array],
      babelrc: false,
      configFile: false,
      cacheIdentifier: 'production:babel-plugin-named-asset-import@:babel-preset-react-app@10.0.0:react-dev-utils@11.0.3:react-scripts@4.0.3',
      plugins: [Array],
      cacheDirectory: true,
      cacheCompression: false,
      compact: true
    }
  },
  {
    test: /\.(js|mjs)$/,
    exclude: /@babel(?:\/|\\{1,2})runtime/,
    loader: 'C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\react-scripts\\node_modules\\babel-loader\\lib\\index.js',
    options: {
      babelrc: false,
      configFile: false,
      compact: false,
      presets: [Array],
      cacheDirectory: true,
      cacheCompression: false,
      cacheIdentifier: 'production:babel-plugin-named-asset-import@:babel-preset-react-app@10.0.0:react-dev-utils@11.0.3:react-scripts@4.0.3',
      sourceMaps: true,
      inputSourceMap: true
    }
  },
  {
    test: /\.css$/,
    exclude: /\.module\.css$/,
    use: [ [Object], [Object], [Object] ],
    sideEffects: true
  },
  { test: /\.module\.css$/, use: [ [Object], [Object], [Object] ] },
  {
    test: /\.(scss|sass)$/,
    exclude: /\.module\.(scss|sass)$/,
    use: [ [Object], [Object], [Object], [Object], [Object] ],
    sideEffects: true
  },
  {
    test: /\.module\.(scss|sass)$/,
    use: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  {
    loader: 'C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\file-loader\\dist\\cjs.js',
    exclude: [ /\.(js|mjs|jsx|ts|tsx)$/, /\.html$/, /\.json$/ ],
    options: { name: 'static/media/[name].[hash:8].[ext]' }
  }
]
Creating an optimized production build...
C:\F\blog\single-spa-cra-example\app2\node_modules\neo-async\async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (C:\F\blog\single-spa-cra-example\app2\node_modules\neo-async\async.js:16:11)
    at C:\F\blog\single-spa-cra-example\app2\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code 1
npm ERR! path C:\F\blog\single-spa-cra-example\app2
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c craco build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACorrales\AppData\Local\npm-cache\_logs\2021-02-23T10_38_44_659Z-debug.log
```

**Comment by hasanayan** [comment]
Sorry the output is not as clear as I expected, could you try logging `webpackConfig.module.rules[1].oneOf[4]` and `webpackConfig.module.rules[1].oneOf[4].use` and post them here.

Also, as a trial for solution. could you please comment line 62 and try if you are getting any errors on craco:build? And if there are no errors could you tell me if there are any css files on the output folder? (there shouldn't be)

**Comment by hasanayan** [comment]
I will also need the exact console output when you get `Error: Callback was already called.` message

**Comment by albertocorrales** [comment]
Hi @hasanayan , I've parsed the whole webpackConfig.module with JSON.stringify. I attach also the console log:
[2021-02-23T17_14_53_930Z-debug.log](https://github.com/hasanayan/craco-plugin-single-spa-application/files/6030710/2021-02-23T17_14_53_930Z-debug.log).

Finally, if I remove line 62 (`cracoConfig.webpack.plugins.remove.push("MiniCssExtractPlugin");`), command `npm run craco:build` works fine.


```
{
    "strictExportPresence": true,
    "rules": [{
        "parser": {
            "requireEnsure": false
        }
    }, {
        "oneOf": [{
            "test": [{}],
            "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\url-loader\\dist\\cjs.js",
            "options": {
                "limit": 10000,
                "mimetype": "image/avif",
                "name": "static/media/[name].[hash:8].[ext]"
            }
        }, {
            "test": [{}, {}, {}, {}],
            "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\url-loader\\dist\\cjs.js",
            "options": {
                "limit": 10000,
                "name": "static/media/[name].[hash:8].[ext]"
            }
        }, {
            "test": {},
            "include": "C:\\F\\blog\\single-spa-cra-example\\app2\\src",
            "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-loader\\lib\\index.js",
            "options": {
                "customize": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-preset-react-app\\webpack-overrides.js",
                "presets": [
                    ["C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-preset-react-app\\index.js", {
                        "runtime": "automatic"
                    }]
                ],
                "babelrc": false,
                "configFile": false,
                "cacheIdentifier": "production:babel-plugin-named-asset-import@0.3.7:babel-preset-react-app@10.0.0:react-dev-utils@11.0.3:react-scripts@4.0.3",
                "plugins": [
                    ["C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-plugin-named-asset-import\\index.js", {
                        "loaderMap": {
                            "svg": {
                                "ReactComponent": "@svgr/webpack?-svgo,+titleProp,+ref![path]"
                            }
                        }
                    }]
                ],
                "cacheDirectory": true,
                "cacheCompression": false,
                "compact": true
            }
        }, {
            "test": {},
            "exclude": {},
            "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-loader\\lib\\index.js",
            "options": {
                "babelrc": false,
                "configFile": false,
                "compact": false,
                "presets": [
                    ["C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\babel-preset-react-app\\dependencies.js", {
                        "helpers": true
                    }]
                ],
                "cacheDirectory": true,
                "cacheCompression": false,
                "cacheIdentifier": "production:babel-plugin-named-asset-import@0.3.7:babel-preset-react-app@10.0.0:react-dev-utils@11.0.3:react-scripts@4.0.3",
                "sourceMaps": true,
                "inputSourceMap": true
            }
        }, {
            "test": {},
            "exclude": {},
            "use": [{
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
                "options": {}
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\css-loader\\dist\\cjs.js",
                "options": {
                    "importLoaders": 1,
                    "sourceMap": true
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\postcss-loader\\src\\index.js",
                "options": {
                    "ident": "postcss",
                    "sourceMap": true
                }
            }],
            "sideEffects": true
        }, {
            "test": {},
            "use": [{
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
                "options": {}
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\css-loader\\dist\\cjs.js",
                "options": {
                    "importLoaders": 1,
                    "sourceMap": true,
                    "modules": {}
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\postcss-loader\\src\\index.js",
                "options": {
                    "ident": "postcss",
                    "sourceMap": true
                }
            }]
        }, {
            "test": {},
            "exclude": {},
            "use": [{
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
                "options": {}
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\css-loader\\dist\\cjs.js",
                "options": {
                    "importLoaders": 3,
                    "sourceMap": true
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\postcss-loader\\src\\index.js",
                "options": {
                    "ident": "postcss",
                    "sourceMap": true
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\resolve-url-loader\\index.js",
                "options": {
                    "sourceMap": true,
                    "root": "C:\\F\\blog\\single-spa-cra-example\\app2\\src"
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\sass-loader\\dist\\cjs.js",
                "options": {
                    "sourceMap": true
                }
            }],
            "sideEffects": true
        }, {
            "test": {},
            "use": [{
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
                "options": {}
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\css-loader\\dist\\cjs.js",
                "options": {
                    "importLoaders": 3,
                    "sourceMap": true,
                    "modules": {}
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\postcss-loader\\src\\index.js",
                "options": {
                    "ident": "postcss",
                    "sourceMap": true
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\resolve-url-loader\\index.js",
                "options": {
                    "sourceMap": true,
                    "root": "C:\\F\\blog\\single-spa-cra-example\\app2\\src"
                }
            }, {
                "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\sass-loader\\dist\\cjs.js",
                "options": {
                    "sourceMap": true
                }
            }]
        }, {
            "loader": "C:\\F\\blog\\single-spa-cra-example\\app2\\node_modules\\file-loader\\dist\\cjs.js",
            "exclude": [{}, {}, {}],
            "options": {
                "name": "static/media/[name].[hash:8].[ext]"
            }
        }]
    }]
}
```

**Comment by hasanayan** [comment]
Here is the problem, search for "mini-css-extract-plugin" in the webpack config dump you just pasted and you will get a few hits. In fact, if this craco plugin worked correctly for you,  there should not be any. The plugin is supposed to find those strings and replace with another so that `style-loader` is used instead of` mini-css-extract-plugin`. 

This behavior works as intended on the machines I have tested it on, even on the repo you shared. But somehow, according to your report, it is not working on your system.

Could you please try to debug `disableCSSExtraction` function in `single-spa-plugin.js` file I asked you to create before? that function is supposed to do the replacement and somehow it is not working.

Also, I just released 1.0.6, I don't think it will solve your problem but you may want to get the latest version into your single-spa-plugin.js as it has slight changes on the `disableCSSExtraction` function.

I can also have a call with you to see the problem on your system and try to fix it. Otherwise, I am out of solutions, unfortunately.

**Comment by albertocorrales** [comment]
Hey @hasanayan, I've tested in two computers and I had the same issue I reported in both, for v1.0.4. However, if I update to version v1.0.6, it works well in my two computers, and I can see CSS in bundle js. So I guess the changes added in latest version have fixed the issue somehow.

If this is working for version v.1.0.6, I think we can close this issue.

Thanks for your help and support.

**Comment by binarykitchen** [comment]
@hasanayan The bug still exists:

```ts
  webpackConfig.module.rules[1].oneOf.forEach((x) => {
                                ^
TypeError: Cannot read properties of undefined (reading 'oneOf')
```

Because there is no rule at index 1, console.log tells me the following:

```
[
  {
    oneOf: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
]
```
